const states = {
    "Karnataka": [
        "KAS",
        "FDA/SDA",
        "JTO",
        "DI",
        "AS",
        "AL",
        "PDO",
        "ACF",
        "AE/JE",
        "CTO",
        "LI",
        "KPSC Group B/C",
        "KPSC Teacher",
        "KCET",
        "K-SET",
        "KEA PSI",
        "VAO",
        "BMTC Conductor",
        "DC Principal",
        "KEA PSU/Board",
        "PC",
        "PSI",
        "FSL SO",
        "Civil Judge",
        "District Judge",
        "Law Clerk",
        "ACS",
        "Typist",
        "SDA (HC)",
        "Driver (HC)",
        "Group D (HC)",
        "Translator (HC)",
        "RA Arbitration",
        "KFD",
        "KSRTC Recruitment",
        "KPTCL/ESCOMs"
    ],
    "Maharashtra": [
        "Rajyaseva (State Service)",
        "PSI, STI, ASO",
        "Tax Assistant, Clerk, Excise PSI",
        "MFSE",
        "MASE",
        "MES",
        "JMFC",
        "AMVI",
        "APP"
    ],
    "Tamil Nadu": [
        "TNPSC Group I",
        "TNPSC Group II/IIA",
        "TNPSC Group IV",
        "TNPSC CES",
        "TNPSC CSS",
        "TNPSC CGS",
        "TNPSC CLIS",
        "TNPSC DEO",
        "TNPSC Technical"
    ],
    "Center": [
        "CSE (IAS, IPS, IFS, etc.)",
        "NEET",
        "IFoS",
        "ESE (IES)",
        "CMS",
        "CDS",
        "NDA & NA",
        "CAPF (AC)",
        "IES/ISS",
        "CGSE",
        "UPSC EPFO",
        "SCRA",
        "LDCE (Internal)"
    ]
};


const boards = {
    "KCET": ["Physics", "Biology", "Chemistry", "Mathematics"],
    "NEET": ["Biology", "Chemistry", "Physics"],
    "JEE": ["Physics", "Chemistry", "Mathematics"],
    "MH-CET": ["Physics", "Chemistry", "Biology", "Mathematics"],
    "TN-Board": ["Physics", "Chemistry", "Mathematics", "Biology"]
};


const examShortNameToIdMap = {
    "Karnataka": {
        "KCET": "kar_kect",
        "KPSC Group B/C": "kar_b_group",
        "KAS": "kar_kas",
        "FDA/SDA": "kar_fda",
        "JTO": "kar_jto",
        "DI": "kar_di",
        "AS": "kar_as",
        "AL": "kar_al",
        "PDO": "kar_pdo",
        "ACF": "kar_acf",
        "AE/JE": "kar_ae",
        "CTO": "kar_cto",
        "LI": "kar_li",
        "KPSC Teacher": "kar_kpsc_teacher",
        "K-SET": "kar_kset",
        "KEA PSI": "kar_kea_psi",
        "VAO": "kar_vao",
        "BMTC Conductor": "kar_bmtc",
        "DC Principal": "kar_dc_principal",
        "KEA PSU/Board": "kar_psu_board",
        "PC": "kar_ksp",
        "PSI": "kar_psi",
        "FSL SO": "kar_fsl",
        "Civil Judge": "kar_hc_civil_judge",
        "District Judge": "kar_hc_district_exam",
        "Law Clerk": "kar_hc_law_clerk",
        "ACS": "kar_hc_acs",
        "Typist": "kar_hc_typists",
        "SDA (HC)": "kar_hc_sda",
        "Driver (HC)": "kar_hc_driver",
        "Group D (HC)": "kar_hc_group_d",
        "Translator (HC)": "kar_hc_translator",
        "RA Arbitration": "kar_hc_ra",
        "KFD": "kar_kfd",
        "KSRTC Recruitment": "kar_ksrtc",
        "KPTCL/ESCOMs": "kar_kptcl"
    },
    "Tamil Nadu": {
        "TNPSC Group I": "tnpsc_group_1",
        "TNPSC Group II/IIA": "tnpsc_group_2",
        "TNPSC Group IV": "tnpsc_group_4",
        "TNPSC CES": "tnpsc_ces",
        "TNPSC CSS": "tnpsc_css",
        "TNPSC CGS": "tnpsc_cgs",
        "TNPSC CLIS": "tnpsc_clis",
        "TNPSC DEO": "tnpsc_deo",
        "TNPSC Technical": "tnpsc_technical"
    },
    "Center": {
        "CSE (IAS, IPS, IFS, etc.)": "upsc_cse",
        "IFoS": "upsc_ifos",
        "ESE (IES)": "upsc_ese",
        "CMS": "upsc_cms",
        "CDS": "upsc_cds",
        "NDA & NA": "upsc_nda",
        "CAPF (AC)": "upsc_capf",
        "IES/ISS": "upsc_ies",
        "CGSE": "upsc_cgse",
        "UPSC EPFO": "upsc_epfo",
        "SCRA": "upsc_scra",
        "LDCE (Internal)": "upsc_ldce",
        "NEET":"upsc_neet"
    }
};
